### PR TITLE
Normalize importer path

### LINKED ISSUE #5: Potential windows bug
We started using this plugin in styled-components, but our [appveyor builds fail consistently](https://ci.appveyor.com/project/mxstbr/styled-components/build/2629/job/altu38ln2ipama5r). The linux ones are all fine though...

Here's our config, for reference:

https://github.com/styled-components/styled-components/blob/master/rollup.config.js#L66-L71

It seems like the fallthrough isn't working quite right? The plugin appears to be failing on the first normal internal import: https://github.com/styled-components/styled-components/blob/a43caefff2b20e98df0464546af80a5267bda9dd/src/index.js#L4

### PR DESCRIPTION
**Pull request by Zalastax**
Closes #5 

Two tests were failing on Windows before, now they don't.
I've also tested the changes live in another project.

### CODE REVIEW

**Comment by AndyOGo** [comment]
@Permutatrix 
Any plan to merge this one and trigger a new release soon?

**Comment by AndyOGo** [comment]
@Permutatrix 
@Zalastax 
Any news on this PR.
We need this bugfix for windows.

May you know if that fork works better at windows? Or if PRs are accepted and maintained over there?
https://www.npmjs.com/package/rollup-plugin-hypothetical-alt
https://github.com/jamesknelson/rollup-plugin-hypothetical

**Comment by Zalastax** [comment]
@AndyOGo feel free to cherry-pick the commit and open a PR over there or create your own fork. You can use a git repository as your dependency if you don't want to publish on NPM.

**Comment by AndyOGo** [comment]
@Zalastax 
Thanks for your quick reply.
That's right, in general any git server could be used. But we are behind a enterprise proxies and this traffic is blocked 😞

**Comment by AndyOGo** [comment]
@Zalastax 
@Permutatrix 
@probablyup

I just published temporary fixed version at npm: [`rollup-plugin-hypothetical-windows-fix@2.1.1`](https://www.npmjs.com/package/rollup-plugin-hypothetical-windows-fix)
And provided another PR #11

**Comment by lemmabit** [comment]
Sorry for the long hiatus. I'll pull this and push a test for it soon.

**Pull request merged**
