### PR TITLE
Fix file id resolution on windows

### PR DESCRIPTION
**Pull request by Hacklone**
Hey,

First of all thanks for this great plugin. :+1: 

On windows files are converted into Unix path style but when loading them they're not converted again.
This PR fixes that issue.

Thanks,
Barna

### CODE REVIEW

**Comment by lemmabit** [comment]
Right, that makes sense, in case you're resolving IDs with another plugin. The PR looks great&mdash;you even included whitespace on the empty line. Thanks for this! I'll add a test for it and publish.

**Comment by Hacklone** [comment]
Thanks, it's a life saver :+1:

**Comment by lemmabit** [comment]
Alright, this is now in v1.1.1.

**Comment by Hacklone** [comment]
Thanks :bow: :)

**Pull request merged**
